import {StyleSheet} from 'react-native';
import {scale} from 'react-native-size-matters';
import {colors} from '../../Theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  button: {
    backgroundColor: colors.lightGreen,
    borderRadius: 4,
    alignItems: 'center',
    width: scale(70),
    justifyContent: 'center',
    height: scale(25),
  },
  modalbtn: {
    backgroundColor: '#85c556',
    width: '90%',
    borderRadius: 5,
    marginTop: scale(20),
  },
  ok: {
    color: colors.white,
    fontWeight: 'bold',
    paddingVertical: 5,
    textAlign: 'center',
  },
  modal: {
    backgroundColor: colors.white,
    marginHorizontal: scale(20),
    alignItems: 'center',
    paddingVertical: scale(20),
    borderRadius: 10,
    justifyContent: 'space-between',
  },
  over: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    flex: 1,
    alignContent: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: colors.white,
    width: 80,
    fontSize: 12,
    textAlign: 'center',
  },
  inputStyle: {
    backgroundColor: 'transparent',
    fontSize: 14,
    paddingHorizontal: 6,
    borderBottomWidth: 0.5,
    borderColor: colors.grey,
    marginBottom: 20,
    borderRadius: 10,
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    height: 48,
    marginTop: 10,
  },
  login: {
    fontSize: 30,
    textAlign: 'center',
    marginTop: '15%',
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: 15,
  },
  con: {marginTop: 80, flex: 1},
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: colors.white,
    marginRight: 14,
    borderRadius: 7,
    width: 160,
    paddingLeft: 10,
    paddingRight: 20,
    marginTop: 5,
  },
  itemContainerVerticle: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 2,
    backgroundColor: colors.white,
    borderRadius: 7,
    paddingLeft: 10,
    paddingRight: 20,
    marginTop: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    margin: 5,
  },
  noItem: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: scale(100),
  },
  checkbox: {
    alignSelf: 'center',
  },
  label: {
    marginLeft: 10,
    fontSize: 11,
    color: colors.black,
  },
  item: {
    backgroundColor: colors.white,
    borderRadius: 10,
    marginBottom: 10,
    marginTop: scale(5),
    elevation: 15,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 10,
    marginHorizontal: 20,
  },
  border: {
    borderLeftWidth: 2,
    borderLeftColor: colors.lightGreen,
    margin: 12,
    paddingLeft: 12,
  },
  row: {flexDirection: 'row', justifyContent: 'space-between'},
  center: {flexDirection: 'row', alignItems: 'center', marginTop: 10},
  text: {
    color: colors.darkGreen,
    fontSize: 11,
    fontWeight: '500',
    marginLeft: 6,
  },
  name: {
    color: colors.black,
    fontSize: 12,
    fontWeight: '500',
    width: scale(150),
  },
  time: {color: colors.black, fontSize: 12, fontWeight: '400'},
  rowSub: {flexDirection: 'row'},
  btnText: {fontSize: 13, color: colors.white, fontWeight: '400'},
  btn: {
    backgroundColor: colors.red,
    borderRadius: 5,
    width: 79,
    height: 23,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  acceptView: {
    borderTopColor: colors.white,
    borderTopWidth: 1,
    backgroundColor: colors.white,
    elevation: 15,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  signBtn: {
    marginVertical: scale(10),
    alignItems: 'center',
    borderRadius: 5,
    width: scale(200),
    alignSelf: 'center',
  },
  signText: {
    color: colors.white,
    paddingVertical: 10,
    fontWeight: '600',
    fontSize: 12,
  },
  img: {
    width: scale(78),
    height: scale(41),
    marginTop: '3%',
    marginHorizontal: 20,
  },
  nameTxt: {
    color: colors.black,
    fontSize: scale(10),
    fontWeight: '500',
  },
  mainView: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginTop: scale(3),
  },
  nameInput: {
    borderBottomColor: colors.black,
    borderBottomWidth: 1,
    fontSize: scale(15),
    color: colors.black,
    width: scale(215),
    paddingVertical: scale(1),
  },
});
