import { StyleSheet } from 'react-native';
import { colors } from '../../Theme/colors';
import { scale } from 'react-native-size-matters';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
    paddingHorizontal: scale(15),
    paddingTop: scale(10),
  },
  overlay: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    flex: 1,
    alignContent: 'center',
    justifyContent: 'center',
  },
  modalButton: {
    backgroundColor: '#85c556',
    width: '90%',
    borderRadius: 5,
  },
  ok: {
    color: 'white',
    fontWeight: 'bold',
    paddingVertical: 5,
    textAlign: 'center',
  },
  modal: {
    backgroundColor: 'white',
    height: '20%',
    marginHorizontal: 20,
    alignItems: 'center',
    paddingVertical: 20,
    borderRadius: 10,
    justifyContent: 'space-between',
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: colors.white,
    paddingHorizontal: scale(15),
    paddingTop: scale(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputStyle: {
    backgroundColor: 'transparent',
    fontSize: 14,
    paddingHorizontal: 6,
    borderBottomWidth: 0.5,
    borderColor: colors.grey,
    marginBottom: 20,
    borderRadius: 10,
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    height: 48,
    marginTop: 10,
  },
  login: {
    fontSize: 30,
    textAlign: 'center',
    marginTop: '25%',
    // fontWeight: 'bold',
  },
  con: {
    flex: 1,
    justifyContent: 'flex-end',
    marginLeft: scale(5),
    marginBottom: scale(5),
  },
  timestamp: {
    color: colors.white,
    fontSize: scale(12),
    // marginBottom: 10,
  },
  gradient: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  coordinates: {
    color: colors.white,
    fontSize: scale(12),
  },
  containerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  button: {
    width: 115,
    backgroundColor: colors.white,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    // paddingVertical: 7,
    flexDirection: 'row',
    height: 30,
    alignContent: 'center',
  },
  buttonText: {
    color: colors.black,
    fontSize: 14,
    marginRight: 7,
  },
  flatListContent: {
    justifyContent: 'space-between',
    flexGrow: 1,
  },
  dateButton: {
    padding: 10,
    marginVertical: 10,
    backgroundColor: colors.white,
    borderRadius: 10,
    alignItems: 'center',
    height: 65,
    paddingTop: 15,
  },
  sheetContainer: { padding: 15 },
  row: { flexDirection: 'row', justifyContent: 'space-between' },
  description: { color: colors.black, fontSize: 16, fontWeight: '600' },
  btn: {
    backgroundColor: colors.lightGreen,
    padding: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  btnText: { color: colors.white, fontSize: 13 },
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
    paddingHorizontal: 4,
  },
  bulletPoint: {
    fontSize: 20,
    marginRight: 10,
    color: colors.black,
  },
  itemText: {
    fontSize: 12,
    color: colors.black,
    paddingHorizontal: scale(12),
  },
  heading: {
    color: colors.black,
    fontWeight: '600',
    fontSize: 12,
    marginBottom: 10,
  },
  headingSub: {
    color: colors.black,
    fontWeight: '600',
    fontSize: 13,
    marginVertical: 7,
  },
  divider: {
    borderTopWidth: 0.5,
    borderColor: colors.black,
    marginVertical: 10,
  },
  rowSub: { flexDirection: 'row', alignItems: 'center' },
  text: { color: colors.darkGreen, fontSize: 11, marginLeft: 6 },
  btnRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  manualButton: { fontSize: 14 },
  download: {
    flexDirection: 'row',
    backgroundColor: colors.black,
    padding: 7,
    borderRadius: 5,
  },
  downloadText: { color: colors.white, fontSize: 12, marginLeft: 5 },
  timer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: scale(10),
  },
  timeContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
  },
  timeText: {
    fontSize: 28,
    // fontWeight: '300',
    color: colors.lightGreen,
    marginRight: 5,
  },
  labelText: {
    fontSize: 16,
    color: colors.black,
  },
  timeContainerSub: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: 10,
  },
  buttonTime: {
    padding: 6,
    borderRadius: 5,
    borderColor: '#3E3E3E33',
    borderWidth: 1,
    width: '45%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  endTimebuttonText: {
    color: colors.black,
    fontSize: 16,
  },

  closeButtonText: {
    color: colors.white,
    fontSize: 16,
  },
  upload: {
    alignItems: 'center',
    height: scale(70),
    backgroundColor: '#C5C5C51A',
    borderColor: '#23232333',
    borderStyle: 'dotted',
    borderWidth: 0.5,
    justifyContent: 'center',
    marginVertical: scale(3),
    borderRadius: 5,
  },
  imageBackground: {
    height: scale(400),
    width: '100%',
    backgroundColor: '#000',
  },
  locationView: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: 20,

    // borderRadius: 10,
  },

  buttonLocate: {
    alignSelf: 'flex-end',
    borderRadius: 6,
    margin: 12,
    backgroundColor: colors.black,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: scale(3),
  },
  buttonTextLocate: {
    color: colors.white,
    paddingVertical: 7,
    paddingHorizontal: 3,
    fontSize: scale(12),
    textAlign: 'center',
  },
  bottomBtn: {
    backgroundColor: colors.lightGreen,
    width: '80%',
    height: 40,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },

  img: {
    height: scale(70),
    width: scale(130),
    alignSelf: 'center',
    marginLeft: scale(70),
  },
});

export default styles;
