import {StyleSheet} from 'react-native';
import {scale} from 'react-native-size-matters';
import {colors} from '../../Theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
    paddingHorizontal: scale(15),
    paddingVertical: scale(15),
  },
  button: {
    alignSelf: 'flex-end',
    borderRadius: 4,
    margin: 12,
  },
  buttonText: {
    color: colors.white,
    paddingVertical: scale(4),
    paddingHorizontal: scale(10),
    fontSize: scale(12),
    textAlign: 'center',
  },
  textInput: {
    height: scale(170),
    backgroundColor: colors.white,
    marginTop: scale(10),
    borderColor: colors.grey,
    borderWidth: 0.5,
    marginHorizontal: scale(12),
    marginBottom: scale(20),
    borderRadius: scale(10),
    padding: scale(10),
    fontSize: scale(13),
    color: colors.black,
  },
  divider: {
    borderWidth: 0.5,
    marginHorizontal: 12,
    borderColor: colors.grey,
    marginVertical: 10,
  },
  inputStyle: {
    backgroundColor: 'transparent',
    fontSize: 14,
    paddingHorizontal: 6,
    borderBottomWidth: 0.5,
    borderColor: colors.grey,
    marginBottom: 20,
    borderRadius: 10,
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    height: 48,
    marginTop: 10,
  },
  noItem: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: scale(100),
  },
  login: {
    fontSize: 30,
    textAlign: 'center',
    marginTop: '15%',
    fontWeight: 'bold',
    color: colors.black,
    marginBottom: 15,
  },
  con: {marginTop: 80, flex: 1},
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: colors.white,
    marginRight: 14,
    borderRadius: 7,
    width: 160,
    paddingLeft: 10,
    paddingRight: 20,
    marginTop: 5,
  },
  itemContainerVerticle: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: colors.white,
    borderRadius: 7,
    paddingLeft: 10,
    paddingRight: 20,
    marginTop: 5,
  },
  checkbox: {
    alignSelf: 'center',
  },
  label: {
    marginLeft: 10,
    fontSize: 11,
    color: colors.black,
  },
  item: {
    backgroundColor: colors.white,
    borderRadius: 10,

    marginTop: '7%',
  },
  border: {
    borderLeftWidth: 2,
    borderLeftColor: colors.lightGreen,
    margin: 12,
    paddingLeft: 12,
  },
  row: {flexDirection: 'row', justifyContent: 'space-between'},
  center: {flexDirection: 'row', alignItems: 'center', marginTop: 10},
  text: {
    color: colors.black,
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 12,
    marginTop: 10,
  },
  signatureText: {
    color: colors.black,
    fontSize: scale(10),
    fontWeight: '500',
  },

  name: {
    color: colors.black,
    fontSize: 12,
    fontWeight: '500',
    width: scale(150),
  },
  time: {color: colors.black, fontSize: 12, fontWeight: '400'},
  rowSub: {flexDirection: 'row'},
  btnText: {fontSize: 13, color: colors.white, fontWeight: '400'},
  btn: {
    backgroundColor: colors.red,
    borderRadius: 5,
    width: 79,
    height: 23,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  nameInput: {
    borderBottomColor: colors.black,
    borderBottomWidth: 1,
    fontSize: scale(15),
    color: colors.black,
    width: scale(215),
    paddingVertical: scale(1),
  },
  mainView: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginTop: scale(3),
  },
  button1: {
    backgroundColor: colors.lightGreen,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    width: scale(110),
  },
});
