export const ticketEvents = [
  {
    id: '1',
    start: new Date(),
    end: new Date(new Date().getTime() + 3600000),
    title: 'Solar Panel Model XYZ-123 Installation',

    children: {
      time: '10:00 AM - 11:00 AM',
      person: 'Brain Siemans',
      address: '123 Main Street, Anytown, USA',
    },
  },

  {
    id: '2',
    start: new Date(new Date().getTime() + 7200000),
    end: new Date(new Date().getTime() + 10800000),
    title: 'Solar Panel Model ABC-456 Maintenance',
    children: {
      time: '12:00 PM - 1:00 PM',
      person: 'Alice Johnson',
      address: '456 Elm Street, Othertown, USA',
    },
  },
];

export const weekList = [
  {
    date: 'May 23',
    day: 'Monday',
    items: [
      {
        id: '1',
        name: 'Solar Panel Model XYZ-123',
        time: '10 : 00 AM - 11 : 00AM',
        person: 'Brain Siemans',
        address: '123 Main Street, Anytown, USA',
      },
      {
        id: '2',
        name: 'event 2',
        time: '10 : 00 AM - 11 : 00AM',
        person: 'Brain Siemans',
        address: '123 Main Street, Anytown, USA',
      },
      {
        id: '3',
        name: 'event 3',
        time: '10 : 00 AM - 11 : 00AM',
        person: 'Brain Siemans',
        address: '123 Main Street, Anytown, USA',
      },
    ],
  },
  {
    date: 'May 24 ',
    day: 'Tuesday',
    items: [
      {
        id: '1',
        name: 'Solar Panel Model XYZ-123',
        time: '10 : 00 AM - 11 : 00AM',
        person: 'Brain Siemans',
        address: '123 Main Street, Anytown, USA',
      },
      {
        id: '2',
        name: 'May 24 Event 2',
        time: '10 : 00 AM - 11 : 00AM',
        person: 'Brain Siemans',
        address: '123 Main Street, Anytown, USA',
      },
    ],
  },
];

export const itemDetail = {
  id: 7,
  name: 'Firewall Breach by a Colossal Threat',
  description:
    '<p>It seems our firewall has been breached, similar to how the Colossal Titan breached Wall Maria. Unauthorized access has been detected, and we need immediate reinforcement to secure our data. Please deploy your best anti-titan (security) squad to resolve this issue and reinforce our defenses.<br></p>',
  team_id: 1,
  use_sla: true,
  team_privacy_visibility: 'portal',
  active: true,
  ticket_type_id: 2,
  tag_ids: [3],
  company_id: 1,
  color: 0,
  kanban_state: 'normal',
  kanban_state_label: 'In Progress',
  legend_blocked: 'Blocked',
  legend_done: 'Ready',
  legend_normal: 'In Progress',
  domain_user_ids: [2],
  user_id: 2,
  properties: false,
  partner_id: 1,
  partner_ticket_ids: [7],
  partner_ticket_count: 0,
  partner_open_ticket_count: 0,
  partner_name: 'My Company',
  partner_email: false,
  partner_phone: '898999',
  commercial_partner_id: 1,
  closed_by_partner: false,
  priority: '3',
  stage_id: 1,
  fold: false,
  date_last_stage_update: '2024-06-03 19:11:27',
  ticket_ref: '07',
  assign_date: '2024-06-03 19:11:54',
  assign_hours: 0,
  close_date: null,
  close_hours: 0,
  open_hours: 190,
  sla_ids: [],
  sla_status_ids: [],
  sla_reached_late: false,
  sla_reached: false,
  sla_deadline: null,
  sla_deadline_hours: 0.0,
  sla_fail: false,
  sla_success: false,
  use_credit_notes: false,
  use_coupons: false,
  use_product_returns: false,
  use_product_repairs: false,
  use_rating: false,
  is_partner_email_update: false,
  is_partner_phone_update: false,
  website_message_ids: [],
  first_response_hours: 0.0,
  avg_response_hours: 0.0,
  oldest_unanswered_customer_message_date: '2024-06-03 19:11:27',
  answered_customer_message_count: 0,
  total_response_hours: 0.0,
  display_extra_info: false,
  create_date: '2024-06-03 19:11:27',
  write_date: '2024-06-03 19:11:54',
};
