import React from "react";
import { NavigatorScreenParams } from "@react-navigation/native";
export enum SCREENS {
  HOME = "HOME",
  BOTTOMNAV = "BOTTOMNAV",
  SPLASH = "SPLASH",
  OTP = "OTP",
  FORGOTPASSWORD = "FORGOTPASSWORD",
  LOGIN = "LOGIN",
  SIGNUP = "SIGNUP",
  JOBSUMMARY = "JOBSUMMARY",
  JOBDETAILS = "JOBDETAILS",
  JOBPROGRESS = "JOBPROGRESS",
  CHECKLIST = "CHECKLIST",
  FINALREMARKS = "FINALREMARKS",
  VANCHECKLIST = "VANCHECKLIST",
  FEEDBACK = "FEEDBACK",
  DETAILS = "DETAILS",
  CUSTOMERFEEDBACK = "CUSTOMERFEEDBACK",
  PHONE = "PHONE",
  DOCUMENT = "DOCUMENT",
  GALLARY = "GALLARY",
  DASHBOARD = "DASHBOARD",
  TICKETSTATUS = "TICKETSTATUS",
  MEDIA = "MEDIA",
  DOCUMENTREADER = "DOCUMENTREADER",
  UPLOADMEDIAAFTERTICKETCOMPLETION = "UPLOADMEDIAAFTERTICKETCOMPLETION",
  SURVEYREADER = "SURVEYREADER",
  EXTRACHECKLIST = "EXTRACHECKLIST",
  RESETPASSWORD = "RESETPASSWORD",
}

export type RootStackParamList = {
  [SCREENS.HOME]: undefined;
  [SCREENS.BOTTOMNAV]: NavigatorScreenParams<TabParamList>;
  [SCREENS.SPLASH]: undefined;
  [SCREENS.OTP]: undefined;
  [SCREENS.FORGOTPASSWORD]: undefined;
  [SCREENS.LOGIN]: undefined;
  [SCREENS.SIGNUP]: undefined;
  [SCREENS.JOBDETAILS]: any;
  [SCREENS.JOBPROGRESS]: any;
  [SCREENS.CHECKLIST]: any;
  [SCREENS.FINALREMARKS]: any;
  [SCREENS.VANCHECKLIST]: any;
  [SCREENS.FEEDBACK]: any;
  [SCREENS.DETAILS]: any;
  [SCREENS.CUSTOMERFEEDBACK]: any;
  [SCREENS.PHONE]: any;
  [SCREENS.DOCUMENT]: any;
  [SCREENS.GALLARY]: any;
  [SCREENS.DASHBOARD]: any;
  [SCREENS.TICKETSTATUS]: any;
  [SCREENS.MEDIA]: any;
  [SCREENS.DOCUMENTREADER]: any;
  [SCREENS.UPLOADMEDIAAFTERTICKETCOMPLETION]: any;
  [SCREENS.SURVEYREADER]: any;
  [SCREENS.RESETPASSWORD]: any;
};
export type TabParamList = {
  [SCREENS.HOME]: undefined;
  [SCREENS.JOBSUMMARY]: undefined;
  [SCREENS.PHONE]: undefined;
  [SCREENS.DOCUMENT]: undefined;
  [SCREENS.GALLARY]: undefined;
  [SCREENS.DASHBOARD]: undefined;
  [SCREENS.MEDIA]: undefined;
};
